[package]
name = "noupling-explorer"
description = "Explorer report format for noupling."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
noupling-core = { path = "../noupling-core" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
globset = { workspace = true }

[dev-dependencies]
noupling-core = { path = "../noupling-core", features = ["test-utils"] }
